### PR TITLE
Add Java Console.log

### LINKED ISSUE #3: Add Java console.log

### PR DESCRIPTION
**Pull request by ajitid**
Fixes #3

### CODE REVIEW

**Comment by lgarron** [comment]
Thanks for the PR!

I have two small requests:
- Could you also add Java to `README.md`?
- Could you make the `Console` class lower-case? If not, could you document that in the `README.md` change?

Thanks!

**Comment by ajitid** [comment]
> Could you make the Console class lower-case? 

Yes I can. Its just that I found you keeping capital case `Log` in Go code.

**Comment by lgarron** [comment]
> Yes I can. Its just that I found you keeping capital case `Log` in Go code.

Yeah, that's because I haven't found a workaround for Go yet: #1 :-(

The main use case here is familiarity at the expense of local language idioms, so I try to use lowercase where possible. (And I should probably document that in `README.md` at this point.)

**Comment by ajitid** [comment]
changes done

**Comment by lgarron** [comment]
Thanks! This is the first PR on the project, so I'm still assembling requirements from memory:

- [x] `$LANG` folder
- [x] `$LANG/test`
  - [ ] A test `Makefile`
  - [ ] A test file that prints `"Value:"` and `1337`. (TODO: #4)
- [ ] Add `$LANG` to the top-level` Makefile

Would you mind also adding the latter?
I can also try to add them myself when I'm not at work.

**Comment by lgarron** [comment]
> I can also try to add them myself when I'm not at work.

Did this on the branch and merged.

Thanks for the contribution! 😊

**Pull request merged**
